name: run_small_dropbox
description: A simple plugin to access Dropbox.
version: 1.0.0
homepage: https://bitbucket.org/farioso_fernando/run_small_dropbox/

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
    http: ^0.13.5
    http_parser: ^4.0.2
    path: ^1.8.3
    universal_io: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
